#!/usr/bin/env python
##########################################################
# HyperClock v4.0 by level6
# https://github.com/lleevveell66/HyperClock
##########################################################

"""
This program will make a full-screened clock with astral
and weather data on your Raspberry Pi screen.
"""

import datetime
import sys
import re
import syslog
import json

from datetime import datetime, timezone
from xml.dom import minidom
from xml.dom.minidom import Document
from subprocess import call
from pygame.locals import *

import pygame

import hyper_config
import get_astral_data_local

DEBUG=1

def debug_print(string_to_print):
    """
    This function will print the supplied string_to_print, if DEBUG == 1
    """

    if DEBUG == 1:
        print(string_to_print)

def build_rgba(color_list):
    """
    This function takes {color_list} in the format of (R,G,B) and returns a pygame.Color
    """

    red, green, blue = color_list.split(',')
    red=int(red)
    green=int(green)
    blue=int(blue)
    return pygame.Color(red, green, blue)

def av_init():
    """
    This function will initialize the audio and video with pygame.  It will
    determine the screen resolution and return the minimum, maximum, and mid 
    values for X and Y, as well as the screen object.
    """

    pygame.init()
    pygame.font.init()
    pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=8192)
    pygame.mouse.set_visible(False)

    my_screen=pygame.display.set_mode((0,0),pygame.FULLSCREEN|pygame.NOFRAME)
    my_display_info=pygame.display.Info()
    print(f"Current Resolution: %s x %s\n" % (my_display_info.current_w,my_display_info.current_h))
    syslog.syslog(syslog.LOG_INFO,f"Current Resolution: %s x %s\n" % (my_display_info.current_w,my_display_info.current_h))
    min_x=0
    max_x=my_display_info.current_w
    mid_x=int(max_x/2)
    min_y=0
    max_y=my_display_info.current_h
    mid_y=int(max_y/2)

    return my_screen, min_x, max_x, min_y, max_y, mid_x, mid_y

def get_current_data():
    """
    This function gets the current weather data from the {astral_data_file} and
    the current indoor temp from the {current_indoor_temp} file
    """

    weather_data_filename=hyper_config.cfg_astral_data_file
    indoor_temp_filename=hyper_config.cfg_indoor_temp_file
    
    unicode_arrows={
        'W': '\u2190',
        'N': '\u2191',
        'E': '\u2192',
        'S': '\u2193',
        'NW': '\u2196',
        'NE': '\u2197',
        'SE': '\u2198',
        'SW': '\u2199',
        'NONE': '\u2022'
    }

    try:
        with open(indoor_temp_filename,'r',encoding="utf-8") as file_handle:
            indoor_temp=file_handle.read()
            indoor_temp=indoor_temp[:-1]
            file_handle.close()

    except FileNotFoundError:
        print(f"Error: The file {indoor_temp_filename} was not found")
        sys.exit(1)
    except PermissionError:
        print(f"Error: Permission denied to read: {indoor_temp_filename}")
        sys.exit(1)
    except UnicodeDecodeError:
        print(f"Error: Could not decode file: {indoor_temp_filename} .  Check encoding.")
        sys.exit(1)
    except IOError as other_error:    # Catch other IO errors
        print(f"IOError: {other_error}")
        sys.exit(1)

    try:
        with open(weather_data_filename,'r',encoding="utf-8") as weather_data_file:
            data = json.load(weather_data_file)
        if data:
            if "current" in data:
                current_datetime = int(data["current"]["datetime"])
                # Convert timestamp to datetime object
                dt_object = datetime.fromtimestamp(current_datetime)
                # Format the date
                last_date = dt_object.strftime("%A %m/%d/%Y")
                # Format the time
                last_time = dt_object.strftime("%I:%M %p")

                sunrise_datetime = int(data["current"]["sunrise"])
                # Convert timestamp to datetime object (UTC)
                dt_object = datetime.fromtimestamp(sunrise_datetime)
                # Format the time
                sunrise = dt_object.strftime("%I:%M %p")

                sunset_datetime = int(data["current"]["sunset"])
                # Convert timestamp to datetime object (UTC)
                dt_object = datetime.fromtimestamp(sunset_datetime, timezone.utc)
                # Format the time
                sunset = dt_object.strftime("%I:%M %p")

                pressure = str(round(data["current"]["pressure"]))
                humidity = str(round(data["current"]["humidity"]))

                current_temp = str(round(data["current"]["temp"]))
                temp_high = str(round(data["current"]["temp_high"]))
                temp_low = str(round(data["current"]["temp_low"]))
                current_condition = data["current"]["condition"]
                current_icon = data["current"]["icon"]

                wind_speed = str(round(data["current"]["wind_speed"]))
                wind_dir = int(data["current"]["wind_dir"])
                
                if wind_dir > 338:                            # (339 - 360) North
                    wind_direction=unicode_arrows['N']
                elif wind_dir > 292:                          # (293 - 338) Nortwest
                    wind_direction=unicode_arrows['NW']
                elif wind_dir > 248:                          # (249 - 337) West
                    wind_direction=unicode_arrows['W']
                elif wind_dir > 202:                          # (203 - 248) Southwest
                    wind_direction=unicode_arrows['SW']
                elif wind_dir > 158:                          # (159 - 202) South
                    wind_direction=unicode_arrows['S']
                elif wind_dir > 112:                          # (113 - 158) Southeast
                    wind_direction=unicode_arrows['SE']
                elif wind_dir > 67:                           # ( 68 - 112) East
                    wind_direction=unicode_arrows['E']
                elif wind_dir > 22:                           # ( 23 -  67) Northeast 
                    wind_direction=unicode_arrows['NE']
                elif wind_dir > 22:                           # (  0 -  22) North 
                    wind_direction=unicode_arrows['N']

                moon_phase_percent = float(data["current"]["moon_phase"])
                if moon_phase_percent >= 0.89:                # (0.89 - 1.00) New Moon
                    moon_phase_num=0
                elif moon_phase_percent >= 0.76:              # (0.76 - 0.88) Waning Crescent
                    moon_phase_num=7
                elif moon_phase_percent >= 0.63:              # (0.63 - 0.75) Last Quarter
                    moon_phase_num=6
                elif moon_phase_percent >= 0.51:              # (0.51 - 0.62) Waning Gibbous
                    moon_phase_num=5 
                elif moon_phase_percent >= 0.39:              # (0.39 - 0.50) Full Moon
                    moon_phase_num=4
                elif moon_phase_percent >= 0.26:              # (0.26 - 0.38) Waxing gibbous
                    moon_phase_num=3
                elif moon_phase_percent >= 0.13:              # (0.13 - 0.25) First Quarter
                    moon_phase_num=2
                elif moon_phase_percent >= 0.00:              # (0.00 - 0.12) Waxing Crescent
                    moon_phase_num=1

                #rising="?"
                #rising_num=int(current.getAttribute("rising"))
                #if rising_num==0:
                #    rising=unicode_arrows['NONE']
                #if rising_num==1:
                #    rising=unicode_arrows['N']
                #if rising_num==2:
                #    rising=unicode_arrows['S']
                rising=unicode_arrows['NONE']

                # base_dir = '/sys/bus/w1/devices/'
                # device_folder = glob.glob(base_dir + '28*')[0]

                day1_code = data["daily"][0]["icon"]
                day1_high = str(round(data["daily"][0]["temp_high"]))
                day1_low = str(round(data["daily"][0]["temp_low"]))
                day1_datetime = data["daily"][0]["datetime"]
                # Convert timestamp to datetime object (UTC)
                dt_object = datetime.fromtimestamp(day1_datetime, timezone.utc)
                # Format the date
                day1_day = dt_object.strftime("%A")

                day2_code = data["daily"][1]["icon"]
                day2_high = str(round(data["daily"][1]["temp_high"]))
                day2_low = str(round(data["daily"][1]["temp_low"]))
                day2_datetime = data["daily"][1]["datetime"]
                # Convert timestamp to datetime object (UTC)
                dt_object = datetime.fromtimestamp(day2_datetime, timezone.utc)
                # Format the date
                day2_day = dt_object.strftime("%A")

                day3_code = data["daily"][2]["icon"]
                day3_high = str(round(data["daily"][2]["temp_high"]))
                day3_low = str(round(data["daily"][2]["temp_low"]))
                day3_datetime = data["daily"][2]["datetime"]
                # Convert timestamp to datetime object (UTC)
                dt_object = datetime.fromtimestamp(day3_datetime, timezone.utc)
                # Format the date
                day3_day = dt_object.strftime("%A")

                day4_code = data["daily"][3]["icon"]
                day4_high = str(round(data["daily"][3]["temp_high"]))
                day4_low = str(round(data["daily"][3]["temp_low"]))
                day4_datetime = data["daily"][3]["datetime"]
                # Convert timestamp to datetime object (UTC)
                dt_object = datetime.fromtimestamp(day4_datetime, timezone.utc)
                # Format the date
                day4_day = dt_object.strftime("%A")

                return {
                    'moon_phase_num': moon_phase_num,
                    'sunrise': sunrise,
                    'sunset': sunset,
                    'code': current_icon,
                    'condition': current_condition,
                    'humidity': humidity,
                    'pressure': pressure,
                    'rising': rising,
                    'indoor': indoor_temp,
                    'temp': current_temp,
                    'wind_direction': wind_direction,
                    'wind_speed': wind_speed,
                    'high': temp_high,
                    'low': temp_low,
                    'day1_code': day1_code,
                    'day1_day': day1_day,
                    'day1_high': day1_high,
                    'day1_low': day1_low,
                    'day2_code': day2_code,
                    'day2_day': day2_day,
                    'day2_high': day2_high,
                    'day2_low': day2_low,
                    'day3_code': day3_code,
                    'day3_day': day3_day,
                    'day3_high': day3_high,
                    'day3_low': day3_low,
                    'day4_code': day4_code,
                    'day4_day': day4_day,
                    'day4_high': day4_high,
                    'day4_low': day4_low,
                    'last_date': last_date,
                    'last_time': last_time
                    }

    except FileNotFoundError:
        print(f"Error: The file {weather_data_filename} was not found")
        sys.exit(1)
    except PermissionError:
        print(f"Error: Permission denied to read: {weather_data_filename}")
        sys.exit(1)
    except UnicodeDecodeError:
        print(f"Error: Could not decode file: {weather_data_filename} .  Check encoding.")
        sys.exit(1)
    except IOError as other_error:    # Catch other IO errors
        print(f"IOError: {other_error}")
        sys.exit(1)

def get_astral_data():
    """
    This function will retreive the astral data
    """

    result=re.match("standalone",hyper_config.cfg_topology,flags=re.I)
    if result is None:
        astral_data_cmd=hyper_config.cfg_astral_data_command
        debug_print(f"Running astral_data_cmd {astral_data_cmd}")
        call(astral_data_cmd,shell=True)
    else:
        debug_print(f"Calling get_astral_data.download_and_write_weather")
        get_astral_data.download_and_write_weather(hyper_config.cfg_woeid)

def get_indoor_temp():
    """
    This function retreives the indoor temperature
    """

    indoor_temp_cmd=hyper_config.cfg_indoor_temp_command
    call(indoor_temp_cmd,shell=True)


get_astral_data()
get_indoor_temp()
current_data=get_current_data()
my_screen, min_x, max_x, min_y, max_y, mid_x, mid_y = av_init()

while True:
    try:
        for event in pygame.event.get():
            if event.type==QUIT:
                pygame.quit()
                sys.exit()

        my_screen.fill((0,0,0))

        seconds=int(datetime.now().strftime("%s"))
        if seconds % 2 == 0:
            current_time=datetime.now().strftime("%I:%M %p")
        else:
            current_time=datetime.now().strftime("%I %M %p")

        current_date=datetime.now().strftime("%A     %m / %d / %Y")

        if seconds % 900 == 0:
            get_astral_data()
            get_indoor_temp()

        if seconds % 900 == 0:
            current_data=get_current_data()

        moon_phase_num=str(current_data['moon_phase_num'])
        sunrise=current_data['sunrise']
        sunset=current_data['sunset']
        code=current_data['code']
        condition=current_data['condition']
        humidity=current_data['humidity']
        pressure=current_data['pressure']
        rising=current_data['rising']
        temp=current_data['temp']
        indoor=current_data['indoor']
        wind_direction=current_data['wind_direction']
        wind_speed=current_data['wind_speed']
        high=current_data['high']
        low=current_data['low']
        day1_code=current_data['day1_code']
        day1_day=current_data['day1_day']
        day1_high=current_data['day1_high']
        day1_low=current_data['day1_low']
        day2_code=current_data['day2_code']
        day2_day=current_data['day2_day']
        day2_high=current_data['day2_high']
        day2_low=current_data['day2_low']
        day3_code=current_data['day3_code']
        day3_day=current_data['day3_day']
        day3_high=current_data['day3_high']
        day3_low=current_data['day3_low']
        day4_code=current_data['day4_code']
        day4_day=current_data['day4_day']
        day4_high=current_data['day4_high']
        day4_low=current_data['day4_low']

        last_date=current_data['last_date']
        last_time=current_data['last_time']

        last='(Last update: '+last_date+' '+last_time+')'

        current_temp=temp+'F'
        current_indoor_temp='Indoor: '+indoor+'F'
        current_high=high
        current_low=low
        current_weather=condition
        day1_weather=day1_day+' '+day1_high+'F/'+day1_low+'F'
        day2_weather=day2_day+' '+day2_high+'F/'+day2_low+'F'
        day3_weather=day3_day+' '+day3_high+'F/'+day3_low+'F'
        day4_weather=day4_day+' '+day4_high+'F/'+day4_low+'F'

        time_size=int(.20*max_x)
        date_size=int(.06*max_x)
        weather_size=int(.06*max_x)
        temp_size=int(.07*max_x)
        indoor_temp_size=int(.03*max_x)
        high_size=int(.03*max_x)
        low_size=int(.03*max_x)
        forecast_size=int(.02*max_x)
        wind_size=int(.04*max_x)
        pressure_size=int(.04*max_x)
        humidity_size=int(.04*max_x)
        sunriseset_size=int(.02*max_x)
        last_size=int(.02*max_x)

        time_font=pygame.font.Font(hyper_config.cfg_time_font,time_size)
        date_font=pygame.font.Font(hyper_config.cfg_date_font,date_size)
        weather_font=pygame.font.Font(hyper_config.cfg_weather_font,weather_size)
        temp_font=pygame.font.Font(hyper_config.cfg_temp_font,temp_size)
        indoor_temp_font=pygame.font.Font(hyper_config.cfg_indoor_temp_font,indoor_temp_size)
        high_font=pygame.font.Font(hyper_config.cfg_high_font,high_size)
        low_font=pygame.font.Font(hyper_config.cfg_low_font,low_size)
        forecast_font=pygame.font.Font(hyper_config.cfg_forecast_font,forecast_size)
        wind_font=pygame.font.Font(hyper_config.cfg_wind_font,wind_size)
        pressure_font=pygame.font.Font(hyper_config.cfg_pressure_font,pressure_size)
        humidity_font=pygame.font.Font(hyper_config.cfg_humidity_font,humidity_size)
        sunriseset_font=pygame.font.Font(hyper_config.cfg_sunriseset_font,sunriseset_size)
        last_font=pygame.font.Font(hyper_config.cfg_last_font,last_size)

        time_text=time_font.render(current_time,True,build_rgba(hyper_config.cfg_time_color))
        date_text=date_font.render(current_date,True,build_rgba(hyper_config.cfg_date_color))
        weather_text=weather_font.render(current_weather,True,build_rgba(hyper_config.cfg_weather_color))
        temp_text=temp_font.render(current_temp,True,build_rgba(hyper_config.cfg_temp_color))
        indoor_temp_text=indoor_temp_font.render(current_indoor_temp,True,build_rgba(hyper_config.cfg_indoor_temp_color))
        high_text=high_font.render(current_high,True,build_rgba(hyper_config.cfg_high_color))
        low_text=low_font.render(current_low,True,build_rgba(hyper_config.cfg_low_color))
        wind_text=wind_font.render(wind_direction+' '+wind_speed+'mph',True,build_rgba(hyper_config.cfg_wind_color))
        pressure_text=wind_font.render(pressure+' '+rising,True,build_rgba(hyper_config.cfg_pressure_color))
        humidity_text=wind_font.render(humidity+'%',True,build_rgba(hyper_config.cfg_humidity_color))
        day1_text=forecast_font.render(day1_weather,True,build_rgba(hyper_config.cfg_day1_color))
        day2_text=forecast_font.render(day2_weather,True,build_rgba(hyper_config.cfg_day2_color))
        day3_text=forecast_font.render(day3_weather,True,build_rgba(hyper_config.cfg_day3_color))
        day4_text=forecast_font.render(day4_weather,True,build_rgba(hyper_config.cfg_day4_color))
        sunrise_text=sunriseset_font.render(sunrise,True,build_rgba(hyper_config.cfg_sunrise_color))
        sunset_text=sunriseset_font.render(sunset,True,build_rgba(hyper_config.cfg_sunset_color))
        last_text=last_font.render(last,True,build_rgba(hyper_config.cfg_last_color))

        time_text_rect=time_text.get_rect()
        date_text_rect=date_text.get_rect()
        weather_text_rect=weather_text.get_rect()
        temp_text_rect=temp_text.get_rect()
        indoor_temp_text_rect=indoor_temp_text.get_rect()
        high_text_rect=high_text.get_rect()
        low_text_rect=low_text.get_rect()
        wind_text_rect=wind_text.get_rect()
        pressure_text_rect=pressure_text.get_rect()
        humidity_text_rect=humidity_text.get_rect()
        day1_text_rect=day1_text.get_rect()
        day2_text_rect=day2_text.get_rect()
        day3_text_rect=day3_text.get_rect()
        day4_text_rect=day4_text.get_rect()
        sunrise_text_rect=sunrise_text.get_rect()
        sunset_text_rect=sunset_text.get_rect()
        last_text_rect=last_text.get_rect()

        FILE_NAME='/usr/local/HyperClock/images/'+str(code)+'.png'
        current_img=pygame.image.load(FILE_NAME)
        current_img=pygame.transform.scale(current_img,(int(.18*max_x),int(.18*max_x)))
        current_img_pos=current_img.get_rect(topright=(mid_x+(int(.04*max_x)),mid_y-(int(.05*max_y))))

        time_text_pos=time_text.get_rect(center=(mid_x,0+(time_size/2)))
        date_text_pos=date_text.get_rect(center=(mid_x,0+time_size+date_size/2))
        weather_text_pos=weather_text.get_rect(midbottom=(mid_x,max_y-forecast_size-int(.30*max_y)))
        temp_text_pos=temp_text.get_rect(midright=(mid_x-(int(.16*max_x)),mid_y+int(.10*max_y)))
        indoor_temp_text_pos=indoor_temp_text.get_rect(midright=(mid_x-(int(.13*max_x)),mid_y+int(.17*max_y)+(indoor_temp_size/2)))
        high_text_pos=high_text.get_rect(midright=(mid_x-int(.13*max_x),mid_y+int(.08*max_y)-(high_size/2)))
        low_text_pos=low_text.get_rect(midright=(mid_x-int(.13*max_x),mid_y+int(.11*max_y)+(low_size/2)))
        wind_text_pos=wind_text.get_rect(topleft=(mid_x+int(.04*max_x),mid_y))
        pressure_text_pos=pressure_text.get_rect(topleft=(mid_x+int(.04*max_x),mid_y+wind_size))
        humidity_text_pos=humidity_text.get_rect(topleft=(mid_x+int(.04*max_x),mid_y+wind_size+pressure_size))
        day1_text_pos=day1_text.get_rect(midbottom=(min_x+int(.18*max_x),max_y))
        day2_text_pos=day2_text.get_rect(midbottom=((mid_x/2)+int(.15*max_x),max_y))
        day3_text_pos=day3_text.get_rect(midbottom=(mid_x+(mid_x/2)-int(.15*max_x),max_y))
        day4_text_pos=day4_text.get_rect(midbottom=(max_x-int(.18*max_x),max_y))
        sunrise_text_pos=sunrise_text.get_rect(midtop=(min_x+int(.11*max_x),mid_y-int(.01*max_x)))
        sunset_text_pos=sunset_text.get_rect(midbottom=(min_x+int(.11*max_x),mid_y+int(.13*max_x)))
        last_text_pos=last_text.get_rect(midtop=(mid_x,mid_y+wind_size+pressure_size+humidity_size+int(.01*max_x)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day1_code)+'.png'
        day1_img=pygame.image.load(FILE_NAME)
        day1_img=pygame.transform.scale(day1_img,(int(.09*max_x),int(.09*max_x)))
        day1_img_pos=day1_img.get_rect(midbottom=(min_x+int(.18*max_x),max_y-int(.03*max_y)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day2_code)+'.png'
        day2_img=pygame.image.load(FILE_NAME)
        day2_img=pygame.transform.scale(day2_img,(int(.09*max_x),int(.09*max_x)))
        day2_img_pos=day2_img.get_rect(midbottom=((mid_x/2)+int(.15*max_x),max_y-int(.03*max_y)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day3_code)+'.png'
        day3_img=pygame.image.load(FILE_NAME)
        day3_img=pygame.transform.scale(day3_img,(int(.09*max_x),int(.09*max_x)))
        day3_img_pos=day3_img.get_rect(midbottom=(mid_x+(mid_x/2)-int(.15*max_x),max_y-int(.03*max_y)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day4_code)+'.png'
        day4_img=pygame.image.load(FILE_NAME)
        day4_img=pygame.transform.scale(day4_img,(int(.09*max_x),int(.09*max_x)))
        day4_img_pos=day4_img.get_rect(midbottom=(max_x-int(.18*max_x),max_y-int(.03*max_y)))

        FILE_NAME='/usr/local/HyperClock/images/sunriseset.png'
        sunriseset_img=pygame.image.load(FILE_NAME)
        sunriseset_img=pygame.transform.scale(sunriseset_img,(int(.09*max_x),int(.09*max_x)))
        sunriseset_img_pos=sunriseset_img.get_rect(center=(min_x+int(.11*max_x),mid_y+int(.10*max_y)))

        FILE_NAME='/usr/local/HyperClock/images/moon/'+moon_phase_num+'.png'
        moon_img=pygame.image.load(FILE_NAME)
        moon_img=pygame.transform.scale(moon_img,(int(.09*max_x),int(.09*max_x)))
        moon_img_pos=moon_img.get_rect(center=(max_x-int(.11*max_x),mid_y+int(.10*max_y)))

        my_screen.blit(time_text,(time_text_pos))
        my_screen.blit(date_text,(date_text_pos))
#        my_screen.blit(weathertext,(weathertext_pos))
        my_screen.blit(temp_text,(temp_text_pos))
        if int(indoor) != 9999:
            my_screen.blit(indoor_temp_text,(indoor_temp_text_pos))
        my_screen.blit(high_text,(high_text_pos))
        my_screen.blit(low_text,(low_text_pos))
        my_screen.blit(wind_text,(wind_text_pos))
        my_screen.blit(pressure_text,(pressure_text_pos))
        my_screen.blit(humidity_text,(humidity_text_pos))
        my_screen.blit(day1_text,(day1_text_pos))
        my_screen.blit(day2_text,(day2_text_pos))
        my_screen.blit(day3_text,(day3_text_pos))
        my_screen.blit(day4_text,(day4_text_pos))
        my_screen.blit(current_img,(current_img_pos))
        my_screen.blit(day1_img,(day1_img_pos))
        my_screen.blit(day2_img,(day2_img_pos))
        my_screen.blit(day3_img,(day3_img_pos))
        my_screen.blit(day4_img,(day4_img_pos))
        my_screen.blit(sunriseset_img,(sunriseset_img_pos))
        my_screen.blit(sunrise_text,(sunrise_text_pos))
        my_screen.blit(sunset_text,(sunset_text_pos))
        my_screen.blit(last_text,(last_text_pos))
        my_screen.blit(moon_img,(moon_img_pos))

        pygame.display.update()

        # time.sleep(1)
        pygame.display.flip()

        hours=int(datetime.now().strftime("%I"))
        minutes=int(datetime.now().strftime("%M"))
        ampm=datetime.now().strftime("%p")
        # if(seconds % 10 == 0):
        if minutes % 60 == 0 and seconds % 60 == 0:
            timesound=pygame.mixer.Sound("/usr/local/HyperClock/audio/TheTimeIs.ogg")
            timesound.set_volume(1.0)
            playing=timesound.play()
            while playing.get_busy():
                pygame.time.delay(1)
            hoursound=pygame.mixer.Sound('/usr/local/HyperClock/audio/'+str(hours)+'.ogg')
            hoursound.set_volume(1.0)
            playing=hoursound.play()
            while playing.get_busy():
                pygame.time.delay(1)
            oclocksound=pygame.mixer.Sound('/usr/local/HyperClock/audio/oclock.ogg')
            oclocksound.set_volume(1.0)
            playing=oclocksound.play()
            while playing.get_busy():
                pygame.time.delay(1)
            ampmsound=pygame.mixer.Sound('/usr/local/HyperClock/audio/'+ampm+'.ogg')
            ampmsound.set_volume(1.0)
            playing=ampmsound.play()
            while playing.get_busy():
                pygame.time.delay(1)

    except KeyboardInterrupt:
        print("Program interrupted by keyboard.  Exiting cleanly.")
        syslog.syslog(syslog.LOG_INFO,"Program interrupted by keyboard.  Exiting cleanly.")
        sys.exit()
