#!/usr/bin/env python
##########################################################
# HyperClock v4.0 by level6
# https://github.com/lleevveell66/HyperClock
##########################################################

"""
This program will make a full-screened clock with astral
and weather data on your Raspberry Pi screen.
"""

import datetime
import sys
import re
import syslog

from datetime import datetime
from xml.dom import minidom
from xml.dom.minidom import Document
from subprocess import call
from pygame.locals import *

import pygame

import hyper_config
import get_astral_data_local

def BuildRGBA(color_list):
    """
    This function takes {color_list} in the format of (R,G,B) and returns a pygame.Color
    """

    red, green, blue = color_list.split(',')
    red=int(red)
    green=int(green)
    blue=int(blue)
    return pygame.Color(red, green, blue)

pygame.init()
pygame.font.init()
pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=2048)
pygame.mouse.set_visible(False)

myscreen=pygame.display.set_mode((0,0),pygame.FULLSCREEN|pygame.NOFRAME)
myDisplayInfo=pygame.display.Info()
print(f"Current Resolution: %s x %s\n" % (myDisplayInfo.current_w,myDisplayInfo.current_h))
syslog.syslog(syslog.LOG_INFO,f"Current Resolution: %s x %s\n" % (myDisplayInfo.current_w,myDisplayInfo.current_h))
minX=0
maxX=myDisplayInfo.current_w
midX=int(maxX/2)
minY=0
maxY=myDisplayInfo.current_h
midY=int(maxY/2)

def get_current_data():
    """
    This function gets the current weather data
    """

    doc=Document()
    doc=minidom.parse(hyper_config.cfg_astral_data_file)

    astral=doc.getElementsByTagName("astral")[0]
    weather=doc.getElementsByTagName("weather")[0]
    current=doc.getElementsByTagName("current")[0]
    day0=doc.getElementsByTagName("day0")[0]
    day1=doc.getElementsByTagName("day1")[0]
    day2=doc.getElementsByTagName("day2")[0]
    day3=doc.getElementsByTagName("day3")[0]
    day4=doc.getElementsByTagName("day4")[0]
    now=doc.getElementsByTagName("now")[0]

    unicode_arrows={
        'W': '\u2190',
        'N': '\u2191',
        'E': '\u2192',
        'S': '\u2193',
        'NW': '\u2196',
        'NE': '\u2197',
        'SE': '\u2198',
        'SW': '\u2199',
        'NONE': '\u2022'
    }

    print(f"Wind Direction: %s " % current.getAttribute("wind_direction"))
    wind_dir_deg=int(current.getAttribute("wind_direction"))
    wind_direction="N"
    if wind_dir_deg>22:
        wind_direction=unicode_arrows['N']
    if wind_dir_deg>67:
        wind_direction=unicode_arrows['E']
    if wind_dir_deg>112:
        wind_direction=unicode_arrows['SE']
    if wind_dir_deg>158:
        wind_direction=unicode_arrows['S']
    if wind_dir_deg>202:
        wind_direction=unicode_arrows['SW']
    if wind_dir_deg>248:
        wind_direction=unicode_arrows['W']
    if wind_dir_deg>292:
        wind_direction=unicode_arrows['NW']
    if wind_dir_deg>338:
        wind_direction=unicode_arrows['N']

    rising="?"
    rising_num=int(current.getAttribute("rising"))
    if rising_num==0:
        rising=unicode_arrows['NONE']
    if rising_num==1:
        rising=unicode_arrows['N']
    if rising_num==2:
        rising=unicode_arrows['S']

#base_dir = '/sys/bus/w1/devices/'
#device_folder = glob.glob(base_dir + '28*')[0]

    indoor_temp_file=hyper_config.cfg_indoor_temp_file

    file_handle=open(indoor_temp_file,'r',encoding="utf-8")
    indoor_temp=file_handle.read()
    indoor_temp=indoor_temp[:-1]
    file_handle.close()

    return {
        'moon_phase': astral.attributes["moon_phase"].value,
        'moon_phase_num': astral.attributes["moon_phase_num"].value,
        'sunrise': astral.attributes["sunrise"].value,
        'sunset': astral.getAttribute("sunset"),
        'code': current.getAttribute("code"),
        'condition': current.getAttribute("condition"),
        'humidity': current.getAttribute("humidity"),
        'pressure': current.getAttribute("pressure"),
        'rising': rising,
        'indoor': indoor_temp,
        'temp': current.getAttribute("temp"),
        'wind_chill': current.getAttribute("wind_chill"),
        'wind_direction': wind_direction,
        'wind_speed': current.getAttribute("wind_speed"),
        'high': day0.getAttribute("high"),
        'low': day0.getAttribute("low"),
        'day1_code': day1.getAttribute("code"),
        'day1_condition': day1.getAttribute("condition"),
        'day1_day': day1.getAttribute("day"),
        'day1_high': day1.getAttribute("high"),
        'day1_low': day1.getAttribute("low"),
        'day2_code': day2.getAttribute("code"),
        'day2_condition': day2.getAttribute("condition"),
        'day2_day': day2.getAttribute("day"),
        'day2_high': day2.getAttribute("high"),
        'day2_low': day2.getAttribute("low"),
        'day3_code': day3.getAttribute("code"),
        'day3_condition': day3.getAttribute("condition"),
        'day3_day': day3.getAttribute("day"),
        'day3_high': day3.getAttribute("high"),
        'day3_low': day3.getAttribute("low"),
        'day4_code': day4.getAttribute("code"),
        'day4_condition': day4.getAttribute("condition"),
        'day4_day': day4.getAttribute("day"),
        'day4_high': day4.getAttribute("high"),
        'day4_low': day4.getAttribute("low"),
        'last_date': now.getAttribute("date"),
        'last_time': now.getAttribute("time")
}

def get_astral_data():
    """
    This function will retreive the astral data
    """

    result=re.match("standalone",hyper_config.cfg_topology,flags=re.I)
    if result is None:
        astral_data_cmd=hyper_config.cfg_astral_data_command
        call(astral_data_cmd,shell=True)

    else:
        get_astral_data.download_and_write_weather(hyper_config.cfg_woeid)

def get_indoor_temp():
    """
    This function retreives the indoor temperature
    """

    indoor_temp_cmd=hyper_config.cfg_indoor_temp_command
    call(indoor_temp_cmd,shell=True)


get_astral_data()
get_indoor_temp()
current_data=get_current_data()


while True:
    try:
        for event in pygame.event.get():
            if event.type==QUIT:
                pygame.quit()
                sys.exit()

        myscreen.fill((0,0,0))

        seconds=int(datetime.now().strftime("%s"))
        if seconds % 2 == 0:
            current_time=datetime.now().strftime("%I:%M %p")
        else:
            current_time=datetime.now().strftime("%I %M %p")

        current_date=datetime.now().strftime("%A     %m / %d / %Y")

        if seconds % 900 == 0:
            get_astral_data()
            get_indoor_temp()

        if seconds % 30 == 0:
            current_data=get_current_data()

        moon_phase=current_data['moon_phase']
        moon_phase_num=current_data['moon_phase_num']
        sunrise=current_data['sunrise']
        sunset=current_data['sunset']

        # Fix what appears to be a bug in the Yahoo Weather API, whereas sunrise/sunset times do not pad with zeros for single digit times
        #if(re.match(".*\d:\d .*",sunrise)):
        #    sunrise=re.sub(':',':0',sunrise);

        #if(re.match(".*\d:\d .*",sunset)):
        #    sunset=re.sub(':',':0',sunset);

        code=current_data['code']
        condition=current_data['condition']
        humidity=current_data['humidity']
        pressure=current_data['pressure']
        rising=current_data['rising']
        temp=current_data['temp']
        indoor=current_data['indoor']
        wind_chill=current_data['wind_chill']
        wind_direction=current_data['wind_direction']
        wind_speed=current_data['wind_speed']
        high=current_data['high']
        low=current_data['low']
        day1_code=current_data['day1_code']
        day1_condition=current_data['day1_condition']
        day1_day=current_data['day1_day']
        day1_high=current_data['day1_high']
        day1_low=current_data['day1_low']
        day2_code=current_data['day2_code']
        day2_condition=current_data['day2_condition']
        day2_day=current_data['day2_day']
        day2_high=current_data['day2_high']
        day2_low=current_data['day2_low']
        day3_code=current_data['day3_code']
        day3_condition=current_data['day3_condition']
        day3_day=current_data['day3_day']
        day3_high=current_data['day3_high']
        day3_low=current_data['day3_low']
        day4_code=current_data['day4_code']
        day4_condition=current_data['day4_condition']
        day4_day=current_data['day4_day']
        day4_high=current_data['day4_high']
        day4_low=current_data['day4_low']
        last_date=current_data['last_date']
        last_time=current_data['last_time']

        last='(Last update: '+last_date+' '+last_time+')'

        current_temp=temp+'F'
        current_indoor_temp='Indoor: '+str(indoor)+'F'
        current_high=high
        current_low=low
        current_weather=condition
        day1_weather=day1_day+' '+day1_high+'F/'+day1_low+'F'
        day2_weather=day2_day+' '+day2_high+'F/'+day2_low+'F'
        day3_weather=day3_day+' '+day3_high+'F/'+day3_low+'F'
        day4_weather=day4_day+' '+day4_high+'F/'+day4_low+'F'

        time_size=int(.20*maxX)
        date_size=int(.06*maxX)
        weather_size=int(.06*maxX)
        temp_size=int(.07*maxX)
        indoor_temp_size=int(.03*maxX)
        high_size=int(.03*maxX)
        low_size=int(.03*maxX)
        forecast_size=int(.02*maxX)
        wind_size=int(.04*maxX)
        pressure_size=int(.04*maxX)
        humidity_size=int(.04*maxX)
        sunriseset_size=int(.02*maxX)
        last_size=int(.02*maxX)

        time_font=pygame.font.Font(hyper_config.cfg_time_font,time_size)
        date_font=pygame.font.Font(hyper_config.cfg_date_font,date_size)
        weather_font=pygame.font.Font(hyper_config.cfg_weather_font,weather_size)
        temp_font=pygame.font.Font(hyper_config.cfg_temp_font,temp_size)
        indoor_temp_font=pygame.font.Font(hyper_config.cfg_indoor_temp_font,indoor_temp_size)
        high_font=pygame.font.Font(hyper_config.cfg_high_font,high_size)
        low_font=pygame.font.Font(hyper_config.cfg_low_font,low_size)
        forecast_font=pygame.font.Font(hyper_config.cfg_forecast_font,forecast_size)
        wind_font=pygame.font.Font(hyper_config.cfg_wind_font,wind_size)
        pressure_font=pygame.font.Font(hyper_config.cfg_pressure_font,pressure_size)
        humidity_font=pygame.font.Font(hyper_config.cfg_humidity_font,humidity_size)
        sunriseset_font=pygame.font.Font(hyper_config.cfg_sunriseset_font,sunriseset_size)
        last_font=pygame.font.Font(hyper_config.cfg_last_font,last_size)

        time_text=time_font.render(current_time,True,BuildRGBA(hyper_config.cfg_time_color))
        date_text=date_font.render(current_date,True,BuildRGBA(hyper_config.cfg_date_color))
        weather_text=weather_font.render(current_weather,True,BuildRGBA(hyper_config.cfg_weather_color))
        temp_text=temp_font.render(current_temp,True,BuildRGBA(hyper_config.cfg_temp_color))
        indoor_temp_text=indoor_temp_font.render(current_indoor_temp,True,BuildRGBA(hyper_config.cfg_indoor_temp_color))
        high_text=high_font.render(current_high,True,BuildRGBA(hyper_config.cfg_high_color))
        low_text=low_font.render(current_low,True,BuildRGBA(hyper_config.cfg_low_color))
        wind_text=wind_font.render(wind_direction+' '+wind_speed+'mph',True,BuildRGBA(hyper_config.cfg_wind_color))
        pressure_text=wind_font.render(pressure+' '+rising,True,BuildRGBA(hyper_config.cfg_pressure_color))
        humidity_text=wind_font.render(humidity+'%',True,BuildRGBA(hyper_config.cfg_humidity_color))
        day1_text=forecast_font.render(day1_weather,True,BuildRGBA(hyper_config.cfg_day1_color))
        day2_text=forecast_font.render(day2_weather,True,BuildRGBA(hyper_config.cfg_day2_color))
        day3_text=forecast_font.render(day3_weather,True,BuildRGBA(hyper_config.cfg_day3_color))
        day4_text=forecast_font.render(day4_weather,True,BuildRGBA(hyper_config.cfg_day4_color))
        sunrise_text=sunriseset_font.render(sunrise,True,BuildRGBA(hyper_config.cfg_sunrise_color))
        sunset_text=sunriseset_font.render(sunset,True,BuildRGBA(hyper_config.cfg_sunset_color))
        last_text=last_font.render(last,True,BuildRGBA(hyper_config.cfg_last_color))

        time_text_rect=time_text.get_rect()
        date_text_rect=date_text.get_rect()
        weather_text_rect=weather_text.get_rect()
        temp_text_rect=temp_text.get_rect()
        indoor_temp_text_rect=indoor_temp_text.get_rect()
        high_text_rect=high_text.get_rect()
        low_text_rect=low_text.get_rect()
        wind_text_rect=wind_text.get_rect()
        pressure_text_rect=pressure_text.get_rect()
        humidity_text_rect=humidity_text.get_rect()
        day1_text_rect=day1_text.get_rect()
        day2_text_rect=day2_text.get_rect()
        day3_text_rect=day3_text.get_rect()
        day4_text_rect=day4_text.get_rect()
        sunrise_text_rect=sunrise_text.get_rect()
        sunset_text_rect=sunset_text.get_rect()
        last_text_rect=last_text.get_rect()

        FILE_NAME='/usr/local/HyperClock/images/'+str(code)+'.png'
        current_img=pygame.image.load(FILE_NAME)
        current_img=pygame.transform.scale(current_img,(int(.18*maxX),int(.18*maxX)))
        current_img_pos=current_img.get_rect(topright=(midX+(int(.04*maxX)),midY-(int(.05*maxY))))

        time_text_pos=time_text.get_rect(center=(midX,0+(time_size/2)))
        date_text_pos=date_text.get_rect(center=(midX,0+time_size+date_size/2))
        weather_text_pos=weather_text.get_rect(midbottom=(midX,maxY-forecast_size-int(.30*maxY)))
        temp_text_pos=temp_text.get_rect(midright=(midX-(int(.16*maxX)),midY+int(.10*maxY)))
        indoor_temp_text_pos=indoor_temp_text.get_rect(midright=(midX-(int(.13*maxX)),midY+int(.17*maxY)+(indoor_temp_size/2)))
        high_text_pos=high_text.get_rect(midright=(midX-int(.13*maxX),midY+int(.08*maxY)-(high_size/2)))
        low_text_pos=low_text.get_rect(midright=(midX-int(.13*maxX),midY+int(.11*maxY)+(low_size/2)))
        wind_text_pos=wind_text.get_rect(topleft=(midX+int(.04*maxX),midY))
        pressure_text_pos=pressure_text.get_rect(topleft=(midX+int(.04*maxX),midY+wind_size))
        humidity_text_pos=humidity_text.get_rect(topleft=(midX+int(.04*maxX),midY+wind_size+pressure_size))
        day1_text_pos=day1_text.get_rect(midbottom=(minX+int(.18*maxX),maxY))
        day2_text_pos=day2_text.get_rect(midbottom=((midX/2)+int(.15*maxX),maxY))
        day3_text_pos=day3_text.get_rect(midbottom=(midX+(midX/2)-int(.15*maxX),maxY))
        day4_text_pos=day4_text.get_rect(midbottom=(maxX-int(.18*maxX),maxY))
        sunrise_text_pos=sunrise_text.get_rect(midtop=(minX+int(.11*maxX),midY-int(.01*maxX)))
        sunset_text_pos=sunset_text.get_rect(midbottom=(minX+int(.11*maxX),midY+int(.13*maxX)))
        last_text_pos=last_text.get_rect(midtop=(midX,midY+wind_size+pressure_size+humidity_size+int(.01*maxX)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day1_code)+'.png'
        day1_img=pygame.image.load(FILE_NAME)
        day1_img=pygame.transform.scale(day1_img,(int(.09*maxX),int(.09*maxX)))
        day1_img_pos=day1_img.get_rect(midbottom=(minX+int(.18*maxX),maxY-int(.03*maxY)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day2_code)+'.png'
        day2_img=pygame.image.load(FILE_NAME)
        day2_img=pygame.transform.scale(day2_img,(int(.09*maxX),int(.09*maxX)))
        day2_img_pos=day2_img.get_rect(midbottom=((midX/2)+int(.15*maxX),maxY-int(.03*maxY)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day3_code)+'.png'
        day3_img=pygame.image.load(FILE_NAME)
        day3_img=pygame.transform.scale(day3_img,(int(.09*maxX),int(.09*maxX)))
        day3_img_pos=day3_img.get_rect(midbottom=(midX+(midX/2)-int(.15*maxX),maxY-int(.03*maxY)))

        FILE_NAME='/usr/local/HyperClock/images/'+str(day4_code)+'.png'
        day4_img=pygame.image.load(FILE_NAME)
        day4_img=pygame.transform.scale(day4_img,(int(.09*maxX),int(.09*maxX)))
        day4_img_pos=day4_img.get_rect(midbottom=(maxX-int(.18*maxX),maxY-int(.03*maxY)))

        FILE_NAME='/usr/local/HyperClock/images/sunriseset.png'
        sunriseset_img=pygame.image.load(FILE_NAME)
        sunriseset_img=pygame.transform.scale(sunriseset_img,(int(.09*maxX),int(.09*maxX)))
        sunriseset_img_pos=sunriseset_img.get_rect(center=(minX+int(.11*maxX),midY+int(.10*maxY)))

        FILE_NAME='/usr/local/HyperClock/images/moon/'+moon_phase_num+'.png'
        moon_img=pygame.image.load(FILE_NAME)
        moon_img=pygame.transform.scale(moon_img,(int(.09*maxX),int(.09*maxX)))
        moon_img_pos=moon_img.get_rect(center=(maxX-int(.11*maxX),midY+int(.10*maxY)))

        myscreen.blit(time_text,(time_text_pos))
        myscreen.blit(date_text,(date_text_pos))
#        myscreen.blit(weathertext,(weathertext_pos))
        myscreen.blit(temp_text,(temp_text_pos))
        if int(indoor) != 9999:
            myscreen.blit(indoor_temp_text,(indoor_temp_text_pos))
        myscreen.blit(high_text,(high_text_pos))
        myscreen.blit(low_text,(low_text_pos))
        myscreen.blit(wind_text,(wind_text_pos))
        myscreen.blit(pressure_text,(pressure_text_pos))
        myscreen.blit(humidity_text,(humidity_text_pos))
        myscreen.blit(day1_text,(day1_text_pos))
        myscreen.blit(day2_text,(day2_text_pos))
        myscreen.blit(day3_text,(day3_text_pos))
        myscreen.blit(day4_text,(day4_text_pos))
        myscreen.blit(current_img,(current_img_pos))
        myscreen.blit(day1_img,(day1_img_pos))
        myscreen.blit(day2_img,(day2_img_pos))
        myscreen.blit(day3_img,(day3_img_pos))
        myscreen.blit(day4_img,(day4_img_pos))
        myscreen.blit(sunriseset_img,(sunriseset_img_pos))
        myscreen.blit(sunrise_text,(sunrise_text_pos))
        myscreen.blit(sunset_text,(sunset_text_pos))
        myscreen.blit(last_text,(last_text_pos))
        myscreen.blit(moon_img,(moon_img_pos))

        pygame.display.update()

#        time.sleep(1)
        pygame.display.flip()

        hours=int(datetime.now().strftime("%I"))
        minutes=int(datetime.now().strftime("%M"))
        ampm=datetime.now().strftime("%p")
#        if(seconds % 10 == 0):
        if minutes % 60 == 0 and seconds % 60 == 0:
            timesound=pygame.mixer.Sound("/usr/local/HyperClock/audio/TheTimeIs.ogg")
            timesound.set_volume(1.0)
            playing=timesound.play()
            while playing.get_busy():
                pygame.time.delay(1)
            hoursound=pygame.mixer.Sound('/usr/local/HyperClock/audio/'+str(hours)+'.ogg')
            hoursound.set_volume(1.0)
            playing=hoursound.play()
            while playing.get_busy():
                pygame.time.delay(1)
            oclocksound=pygame.mixer.Sound('/usr/local/HyperClock/audio/oclock.ogg')
            oclocksound.set_volume(1.0)
            playing=oclocksound.play()
            while playing.get_busy():
                pygame.time.delay(1)
            ampmsound=pygame.mixer.Sound('/usr/local/HyperClock/audio/'+ampm+'.ogg')
            ampmsound.set_volume(1.0)
            playing=ampmsound.play()
            while playing.get_busy():
                pygame.time.delay(1)

    except KeyboardInterrupt:
        print("Program interrupted by keyboard.  Exiting cleanly.")
        syslog.syslog(syslog.LOG_INFO,"Program interrupted by keyboard.  Exiting cleanly.")
        sys.exit()
