#####################################################################
# HyperClock.conf - Configuration for HyperClock 4.0 by level6
# https://github.com/lleevveell66/HyperClock
#####################################################################

[HyperClock]

# This defines how HyperClock will retreive the Astral Data, every 15 minutes.  
#   standalone = Use the included GetAstralData module to grab this data locally
#    networked = Use the shell command defined in "AstralDataCommand" (below) to 
#                grab this data.  This allows for a centralized Astral Data deposit, so the Yahoo!
#                weather API is not overwhelmed, in case you have multiple HyperClocks running. 
# Either way, the Astral Data should be deposited into the file defined by AstralDataFile, below.
topology = networked

# Defines the location of the XML file which contains the Astral Data
astral_data_file = /usr/local/HyperClock/AstralData.txt

# Defines the external script to used to retreive the XML from a central source, usually in a networked scenario
astral_data_command = /usr/local/HyperClock/GetWeather.sh

# Defines the location of the text file which contains the Current Indoor Temperature
indoor_temp_file = /usr/local/HyperClock/CurrentIndoorTemp

# Defines the external command used to retreive the Indoor Temperature 
indoor_temp_command = /usr/local/HyperClock/GetIndoorTemp.sh

# Find the woeid for your area, here:
# http://woeid.rosselliot.co.nz/
# http://woeid.factormystic.net/
woeid = 2480733

# Font locations
time_font = /usr/local/HyperClock/fonts/digital-7-mono.ttf
date_font = /usr/local/HyperClock/fonts/DroidSans.ttf
weather_font = /usr/local/HyperClock/fonts/DroidSans.ttf
temp_font = /usr/local/HyperClock/fonts/DroidSans.ttf
indoor_temp_font = /usr/local/HyperClock/fonts/DroidSans.ttf
high_font = /usr/local/HyperClock/fonts/DroidSans.ttf
low_font = /usr/local/HyperClock/fonts/DroidSans.ttf
forecast_font = /usr/local/HyperClock/fonts/DroidSans.ttf
wind_font = /usr/local/HyperClock/fonts/DejaVuSansMono.ttf
pressure_font = /usr/local/HyperClock/fonts/DroidSans.ttf
humidity_font = /usr/local/HyperClock/fonts/DroidSans.ttf
sunriseset_font = /usr/local/HyperClock/fonts/DroidSans.ttf
last_font = /usr/local/HyperClock/fonts/DroidSans.ttf

# More color sets available in themes/ directory
# HyperClock Theme - Midnight Forest
# Colors in Red, Green, Blue
time_color = 244,122,66
date_color = 240,240,30
weather_color = 255,255,128
temp_color = 255,167,45
indoor_temp_color = 240,170,60
high_color = 255,209,45
low_color = 193,154,13
wind_color = 206,95,68
pressure_color = 181,82,57
humidity_color = 160,69,46
day1_color = 255,128,255
day2_color = 255,128,255
day3_color = 255,128,255
day4_color = 255,128,255
sunrise_color = 255,225,0
sunset_color = 255,178,0
last_color = 50,89,58
